AY2425S2-CS2103T-T13-1/tp

docs/AboutUs.md, docs/team/zonghua.md
=> Update AboutUs.md and made portfolio file

docs/AboutUs.md, docs/team/cloudkai.md
=> Update aboutus and Add cloudkai.md

README.md
=> Update link of Github Actions build status badge

docs/DeveloperGuide.md
Closes #35. Updated NFRs to suit our project, and split them according to categories
=> Update NFRs in DeveloperGuide.md

docs/DeveloperGuide.md
=> DG: Add Use Cases - Use Cases 5-9

docs/_config.yml, docs/_sass/minima/_base.scss
=> Update title to FitFlow in _config.yml and _base.scss

docs/DeveloperGuide.md
=> Add Use Case 1-4 in Developer Guide

docs/DeveloperGuide.md
=> Add use cases and a term to glossary

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/RecurringSchedule.java, src/main/java/seedu/address/storage/JsonAdaptedRecurringSchedule.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/RecurringScheduleTest.java
=> Implement time check and day formatter

src/main/java/seedu/address/ui/HelpWindow.java
=> Update help tab link

src/main/java/seedu/address/logic/commands/DisplayCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DisplayCommandParser.java, src/test/java/seedu/address/logic/commands/DisplayCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DisplayCommandParserTest.java
=> Add Display command

src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/model/person/OneTimeSchedule.java, src/main/java/seedu/address/model/person/ScheduleContainsKeywordPredicate.java, src/main/java/seedu/address/storage/JsonAdaptedOneTimeSchedule.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java, src/test/java/seedu/address/model/person/OneTimeScheduleTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
close #103 
To change the date of otsched to LocalDate, timing is kept as String
=> Update otsched date to be LocalDate instead of string

src/main/java/seedu/address/model/util/DayOfWeek.java
=> Fix minor bug left from debugging

build.gradle, src/main/java/seedu/address/MainApp.java
=> Update version number in project

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java
Closes #108. Make sure to delete data folder after merging
=> Bugfix for duplicate phone numbers existing

docs/UserGuide.md
=> Update UserGuide to include note about conflicting schedules

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/person/ScheduleConflictDetector.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/person/ScheduleConflictDetectorTest.java
=> Add internal schedule conflict detection

src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/parser/HelpCommandParser.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
=> Bugfix for Help command with invalid command parameter

docs/DeveloperGuide.md
=> Add display client's details use case

docs/DeveloperGuide.md
=> Edit grammatical error

docs/UserGuide.md
=> Update UG to fix typo and Command summary

docs/UserGuide.md
=> Modify formatting of blocks in UG

docs/UserGuide.md
=> Add hyperlink to edit section under Add Command

docs/DeveloperGuide.md
=> Fix use case bugs

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/OneTimeSchedule.java, src/main/java/seedu/address/model/util/LocalDateUtils.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/util/LocalDateUtilsTest.java
close #173 
Should throw an error if the day does not match the correct month e.g. 31/06/25 should be invalid
=> Date parsing bug

docs/DeveloperGuide.md
Close #146 
Update DG's Acknowledgement section from index.md
=> Update Developer Guide Acknowledgement section

docs/UserGuide.md
Close #193 
Reformat Developer Guide's punctuation formatting
=> Update DG punctuation formatting

docs/UserGuide.md
Close #191 
Fix grammatical errors for Developer Guide
=> Update DG grammatical errors

docs/UserGuide.md
Close #132 
Did testing for popular client managing apps and collated information on the pain points personal trainers might face and how FitFlow addresses these problems.
=> Update UG Introduction

src/main/java/seedu/address/model/person/MedicalHistory.java
Close #187 
Update Medical History VALIDATION_REGEX's comments to keep it consistent with the other fields in the Person Model.
=> Update Medical History VALIDATION_REGEX Comment

build.gradle, docs/UserGuide.md, src/main/java/seedu/address/MainApp.java
=> Update version number and edit UG

docs/DeveloperGuide.md
=> Planned Enhancements Appendix

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DisplayCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java
=> Update INDEX to indicate strictly 1 and above

docs/UserGuide.md, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
=> Update Tags format to allow for all ASCII characters

docs/DeveloperGuide.md, docs/UserGuide.md
=> 201 pagebreak

build.gradle, docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/MainApp.java
Close #273 
Update FitFlow version to 1.6.
=> Branch version release1.6
